use zelda3::ZeldaState;

pub(crate) fn format_render_ppu_summary(state: &ZeldaState) -> String {
    let ppu = &state.ppu;
    format!(
        "mode={} forced_blank={} blank_lines={} brightness={} mosaic={:02x}/{} screen={:02x}/{:02x} window={:02x}/{:02x} math={:02x} cg={:02x}/{:02x} fixed=({:02x},{:02x},{:02x}) obj=({:04x},{:04x},size={}) m7={:04x},{:04x},{:04x},{:04x},{:04x},{:04x},{:04x},{:04x} bg1=({:04x},{:04x},tm={:04x},chr={:04x},map={}x{}) bg2=({:04x},{:04x},tm={:04x},chr={:04x},map={}x{}) bg3=({:04x},{:04x},tm={:04x},chr={:04x},map={}x{}) bg4=({:04x},{:04x},tm={:04x},chr={:04x},map={}x{}) hdma={:02x} dma6={:02x}:{:04x}->{:02x} dma7={:02x}:{:04x}->{:02x} cgram0={:04x} cgram1={:04x} vram0000={:04x} vram1000={:04x}",
        ppu.mode,
        ppu.forced_blank,
        ppu.forced_blank_scanlines,
        ppu.brightness,
        ppu.mosaic_enabled,
        ppu.mosaic_size,
        ppu.screen_enabled[0],
        ppu.screen_enabled[1],
        ppu.screen_windowed[0],
        ppu.screen_windowed[1],
        ppu.math_enabled,
        ppu.clip_mode,
        ppu.prevent_math_mode,
        ppu.fixed_color_r,
        ppu.fixed_color_g,
        ppu.fixed_color_b,
        ppu.obj_tile_adr1,
        ppu.obj_tile_adr2,
        ppu.obj_size,
        ppu.m7_matrix[0] as u16,
        ppu.m7_matrix[1] as u16,
        ppu.m7_matrix[2] as u16,
        ppu.m7_matrix[3] as u16,
        ppu.m7_matrix[4] as u16,
        ppu.m7_matrix[5] as u16,
        ppu.m7_matrix[6] as u16,
        ppu.m7_matrix[7] as u16,
        ppu.bg_layer[0].h_scroll,
        ppu.bg_layer[0].v_scroll,
        ppu.bg_layer[0].tilemap_adr,
        ppu.bg_layer[0].tile_adr,
        if ppu.bg_layer[0].tilemap_wider { 64 } else { 32 },
        if ppu.bg_layer[0].tilemap_higher { 64 } else { 32 },
        ppu.bg_layer[1].h_scroll,
        ppu.bg_layer[1].v_scroll,
        ppu.bg_layer[1].tilemap_adr,
        ppu.bg_layer[1].tile_adr,
        if ppu.bg_layer[1].tilemap_wider { 64 } else { 32 },
        if ppu.bg_layer[1].tilemap_higher { 64 } else { 32 },
        ppu.bg_layer[2].h_scroll,
        ppu.bg_layer[2].v_scroll,
        ppu.bg_layer[2].tilemap_adr,
        ppu.bg_layer[2].tile_adr,
        if ppu.bg_layer[2].tilemap_wider { 64 } else { 32 },
        if ppu.bg_layer[2].tilemap_higher { 64 } else { 32 },
        ppu.bg_layer[3].h_scroll,
        ppu.bg_layer[3].v_scroll,
        ppu.bg_layer[3].tilemap_adr,
        ppu.bg_layer[3].tile_adr,
        if ppu.bg_layer[3].tilemap_wider { 64 } else { 32 },
        if ppu.bg_layer[3].tilemap_higher { 64 } else { 32 },
        state.ram[0x9b],
        state.dma.channel[6].a_bank,
        state.dma.channel[6].a_adr,
        state.dma.channel[6].b_adr,
        state.dma.channel[7].a_bank,
        state.dma.channel[7].a_adr,
        state.dma.channel[7].b_adr,
        ppu.cgram[0],
        ppu.cgram[1],
        ppu.vram[0],
        ppu.vram[0x1000],
    )
}
