//! Debug tracing helpers ported from `zelda3/snes/tracing.c`.

use crate::apu::ApuState;
use crate::snes::Snes;

const CPU_OPCODE_NAMES: [&str; 256] = [
    "brk          ",
    "ora ($%02x,x)  ",
    "cop #$%02x     ",
    "ora $%02x,s    ",
    "tsb $%02x      ",
    "ora $%02x      ",
    "asl $%02x      ",
    "ora [$%02x]    ",
    "php          ",
    "ora #$%04x   ",
    "asl          ",
    "phd          ",
    "tsb $%04x    ",
    "ora $%04x    ",
    "asl $%04x    ",
    "ora $%06x  ",
    "bpl $%04x    ",
    "ora ($%02x),y  ",
    "ora ($%02x)    ",
    "ora ($%02x,s),y",
    "trb $%02x      ",
    "ora $%02x,x    ",
    "asl $%02x,x    ",
    "ora [$%02x],y  ",
    "clc          ",
    "ora $%04x,y  ",
    "inc          ",
    "tcs          ",
    "trb $%04x    ",
    "ora $%04x,x  ",
    "asl $%04x,x  ",
    "ora $%06x,x",
    "jsr $%04x    ",
    "and ($%02x,x)  ",
    "jsl $%06x  ",
    "and $%02x,s    ",
    "bit $%02x      ",
    "and $%02x      ",
    "rol $%02x      ",
    "and [$%02x]    ",
    "plp          ",
    "and #$%04x   ",
    "rol          ",
    "pld          ",
    "bit $%04x    ",
    "and $%04x    ",
    "rol $%04x    ",
    "and $%06x  ",
    "bmi $%04x    ",
    "and ($%02x),y  ",
    "and ($%02x)    ",
    "and ($%02x,s),y",
    "bit $%02x,x    ",
    "and $%02x,x    ",
    "rol $%02x,x    ",
    "and [$%02x],y  ",
    "sec          ",
    "and $%04x,y  ",
    "dec          ",
    "tsc          ",
    "bit $%04x,x  ",
    "and $%04x,x  ",
    "rol $%04x,x  ",
    "and $%06x,x",
    "rti          ",
    "eor ($%02x,x)  ",
    "wdm #$%02x     ",
    "eor $%02x,s    ",
    "mvp $%02x, $%02x ",
    "eor $%02x      ",
    "lsr $%02x      ",
    "eor [$%02x]    ",
    "pha          ",
    "eor #$%04x   ",
    "lsr          ",
    "phk          ",
    "jmp $%04x    ",
    "eor $%04x    ",
    "lsr $%04x    ",
    "eor $%06x  ",
    "bvc $%04x    ",
    "eor ($%02x),y  ",
    "eor ($%02x)    ",
    "eor ($%02x,s),y",
    "mvn $%02x, $%02x ",
    "eor $%02x,x    ",
    "lsr $%02x,x    ",
    "eor [$%02x],y  ",
    "cli          ",
    "eor $%04x,y  ",
    "phy          ",
    "tcd          ",
    "jml $%06x  ",
    "eor $%04x,x  ",
    "lsr $%04x,x  ",
    "eor $%06x,x",
    "rts          ",
    "adc ($%02x,x)  ",
    "per $%04x    ",
    "adc $%02x,s    ",
    "stz $%02x      ",
    "adc $%02x      ",
    "ror $%02x      ",
    "adc [$%02x]    ",
    "pla          ",
    "adc #$%04x   ",
    "ror          ",
    "rtl          ",
    "jmp ($%04x)  ",
    "adc $%04x    ",
    "ror $%04x    ",
    "adc $%06x  ",
    "bvs $%04x    ",
    "adc ($%02x),y  ",
    "adc ($%02x)    ",
    "adc ($%02x,s),y",
    "stz $%02x,x    ",
    "adc $%02x,x    ",
    "ror $%02x,x    ",
    "adc [$%02x],y  ",
    "sei          ",
    "adc $%04x,y  ",
    "ply          ",
    "tdc          ",
    "jmp ($%04x,x)",
    "adc $%04x,x  ",
    "ror $%04x,x  ",
    "adc $%06x,x",
    "bra $%04x    ",
    "sta ($%02x,x)  ",
    "brl $%04x    ",
    "sta $%02x,s    ",
    "sty $%02x      ",
    "sta $%02x      ",
    "stx $%02x      ",
    "sta [$%02x]    ",
    "dey          ",
    "bit #$%04x   ",
    "txa          ",
    "phb          ",
    "sty $%04x    ",
    "sta $%04x    ",
    "stx $%04x    ",
    "sta $%06x  ",
    "bcc $%04x    ",
    "sta ($%02x),y  ",
    "sta ($%02x)    ",
    "sta ($%02x,s),y",
    "sty $%02x,x    ",
    "sta $%02x,x    ",
    "stx $%02x,y    ",
    "sta [$%02x],y  ",
    "tya          ",
    "sta $%04x,y  ",
    "txs          ",
    "txy          ",
    "stz $%04x    ",
    "sta $%04x,x  ",
    "stz $%04x,x  ",
    "sta $%06x,x",
    "ldy #$%04x   ",
    "lda ($%02x,x)  ",
    "ldx #$%04x   ",
    "lda $%02x,s    ",
    "ldy $%02x      ",
    "lda $%02x      ",
    "ldx $%02x      ",
    "lda [$%02x]    ",
    "tay          ",
    "lda #$%04x   ",
    "tax          ",
    "plb          ",
    "ldy $%04x    ",
    "lda $%04x    ",
    "ldx $%04x    ",
    "lda $%06x  ",
    "bcs $%04x    ",
    "lda ($%02x),y  ",
    "lda ($%02x)    ",
    "lda ($%02x,s),y",
    "ldy $%02x,x    ",
    "lda $%02x,x    ",
    "ldx $%02x,y    ",
    "lda [$%02x],y  ",
    "clv          ",
    "lda $%04x,y  ",
    "tsx          ",
    "tyx          ",
    "ldy $%04x,x  ",
    "lda $%04x,x  ",
    "ldx $%04x,y  ",
    "lda $%06x,x",
    "cpy #$%04x   ",
    "cmp ($%02x,x)  ",
    "rep #$%02x     ",
    "cmp $%02x,s    ",
    "cpy $%02x      ",
    "cmp $%02x      ",
    "dec $%02x      ",
    "cmp [$%02x]    ",
    "iny          ",
    "cmp #$%04x   ",
    "dex          ",
    "wai          ",
    "cpy $%04x    ",
    "cmp $%04x    ",
    "dec $%04x    ",
    "cmp $%06x  ",
    "bne $%04x    ",
    "cmp ($%02x),y  ",
    "cmp ($%02x)    ",
    "cmp ($%02x,s),y",
    "pei $%02x      ",
    "cmp $%02x,x    ",
    "dec $%02x,x    ",
    "cmp [$%02x],y  ",
    "cld          ",
    "cmp $%04x,y  ",
    "phx          ",
    "stp          ",
    "jml [$%04x]  ",
    "cmp $%04x,x  ",
    "dec $%04x,x  ",
    "cmp $%06x,x",
    "cpx #$%04x   ",
    "sbc ($%02x,x)  ",
    "sep #$%02x     ",
    "sbc $%02x,s    ",
    "cpx $%02x      ",
    "sbc $%02x      ",
    "inc $%02x      ",
    "sbc [$%02x]    ",
    "inx          ",
    "sbc #$%04x   ",
    "nop          ",
    "xba          ",
    "cpx $%04x    ",
    "sbc $%04x    ",
    "inc $%04x    ",
    "sbc $%06x  ",
    "beq $%04x    ",
    "sbc ($%02x),y  ",
    "sbc ($%02x)    ",
    "sbc ($%02x,s),y",
    "pea #$%04x   ",
    "sbc $%02x,x    ",
    "inc $%02x,x    ",
    "sbc [$%02x],y  ",
    "sed          ",
    "sbc $%04x,y  ",
    "plx          ",
    "xce          ",
    "jsr ($%04x,x)",
    "sbc $%04x,x  ",
    "inc $%04x,x  ",
    "sbc $%06x,x",
];

const CPU_OPCODE_NAMES_SP: [Option<&str>; 256] = [
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("ora #$%02x     "),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("and #$%02x     "),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("eor #$%02x     "),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("adc #$%02x     "),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("bit #$%02x     "),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("ldy #$%02x     "),
    None,
    Some("ldx #$%02x     "),
    None,
    None,
    None,
    None,
    None,
    None,
    Some("lda #$%02x     "),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("cpy #$%02x     "),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("cmp #$%02x     "),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("cpx #$%02x     "),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("sbc #$%02x     "),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
];

const CPU_OPCODE_TYPE: [u8; 256] = [
    0, 1, 1, 1, 1, 1, 1, 1, 0, 4, 0, 0, 2, 2, 2, 3, 6, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 0, 2, 2, 2, 3,
    2, 1, 3, 1, 1, 1, 1, 1, 0, 4, 0, 0, 2, 2, 2, 3, 6, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 0, 2, 2, 2, 3,
    0, 1, 1, 1, 8, 1, 1, 1, 0, 4, 0, 0, 2, 2, 2, 3, 6, 1, 1, 1, 8, 1, 1, 1, 0, 2, 0, 0, 3, 2, 2, 3,
    0, 1, 7, 1, 1, 1, 1, 1, 0, 4, 0, 0, 2, 2, 2, 3, 6, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 0, 2, 2, 2, 3,
    6, 1, 7, 1, 1, 1, 1, 1, 0, 4, 0, 0, 2, 2, 2, 3, 6, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 0, 2, 2, 2, 3,
    5, 1, 5, 1, 1, 1, 1, 1, 0, 4, 0, 0, 2, 2, 2, 3, 6, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 0, 2, 2, 2, 3,
    5, 1, 1, 1, 1, 1, 1, 1, 0, 4, 0, 0, 2, 2, 2, 3, 6, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 0, 2, 2, 2, 3,
    5, 1, 1, 1, 1, 1, 1, 1, 0, 4, 0, 0, 2, 2, 2, 3, 6, 1, 1, 1, 2, 1, 1, 1, 0, 2, 0, 0, 2, 2, 2, 3,
];

const SPC_OPCODE_NAMES: [&str; 256] = [
    "nop              ",
    "tcall 0          ",
    "set1 $%02x.0       ",
    "bbs $%02x.0, $%04x ",
    "or a, $%02x        ",
    "or a, $%04x      ",
    "or a, [X]        ",
    "or a, [$%02x+x]    ",
    "or a, #$%02x       ",
    "or $%02x, $%02x      ",
    "or1 c, $%04x.%01x   ",
    "asl $%02x          ",
    "asl $%04x        ",
    "push p           ",
    "tset $%04x       ",
    "brk              ",
    "bpl $%04x        ",
    "tcall 1          ",
    "clr1 $%02x.0       ",
    "bbc $%02x.0, $%04x ",
    "or a, $%02x+x      ",
    "or a, $%04x+x    ",
    "or a, $%04x+y    ",
    "or a, [$%02x]+y    ",
    "or $%02x, #$%02x     ",
    "or [X], [Y]      ",
    "decw $%02x         ",
    "asl $%02x+x        ",
    "asl a            ",
    "dec x            ",
    "cmp x, $%04x     ",
    "jmp [$%04x+x]    ",
    "clrp             ",
    "tcall 2          ",
    "set1 $%02x.1       ",
    "bbs $%02x.1, $%04x ",
    "and a, $%02x       ",
    "and a, $%04x     ",
    "and a, [X]       ",
    "and a, [$%02x+x]   ",
    "and a, #$%02x      ",
    "and $%02x, $%02x     ",
    "or1 c, /$%04x.%01x  ",
    "rol $%02x          ",
    "rol $%04x        ",
    "push a           ",
    "cbne $%02x, $%04x  ",
    "bra $%04x        ",
    "bmi $%04x        ",
    "tcall 3          ",
    "clr1 $%02x.1       ",
    "bbc $%02x.1, $%04x ",
    "and a, $%02x+x     ",
    "and a, $%04x+x   ",
    "and a, $%04x+y   ",
    "and a, [$%02x]+y   ",
    "and $%02x, #$%02x    ",
    "and [X], [Y]     ",
    "incw $%02x         ",
    "rol $%02x+x        ",
    "rol a            ",
    "inc x            ",
    "cmp x, $%02x       ",
    "call $%04x       ",
    "setp             ",
    "tcall 4          ",
    "set1 $%02x.2       ",
    "bbs $%02x.2, $%04x ",
    "eor a, $%02x       ",
    "eor a, $%04x     ",
    "eor a, [X]       ",
    "eor a, [$%02x+x]   ",
    "eor a, #$%02x      ",
    "eor $%02x, $%02x     ",
    "and1 c, $%04x.%01x  ",
    "lsr $%02x          ",
    "lsr $%04x        ",
    "push x           ",
    "tclr $%04x       ",
    "pcall $%02x        ",
    "bvc $%04x        ",
    "tcall 5          ",
    "clr1 $%02x.2       ",
    "bbc $%02x.2, $%04x ",
    "eor a, $%02x+x     ",
    "eor a, $%04x+x   ",
    "eor a, $%04x+y   ",
    "eor a, [$%02x]+y   ",
    "eor $%02x, #$%02x    ",
    "eor [X], [Y]     ",
    "cmpw ya, $%02x     ",
    "lsr $%02x+x        ",
    "lsr a            ",
    "mov x, a         ",
    "cmp y, $%04x     ",
    "jmp $%04x        ",
    "clrc             ",
    "tcall 6          ",
    "set1 $%02x.3       ",
    "bbs $%02x.3, $%04x ",
    "cmp a, $%02x       ",
    "cmp a, $%04x     ",
    "cmp a, [X]       ",
    "cmp a, [$%02x+x]   ",
    "cmp a, #$%02x      ",
    "cmp $%02x, $%02x     ",
    "and1 c, /$%04x.%01x ",
    "ror $%02x          ",
    "ror $%04x        ",
    "push y           ",
    "dbnz $%02x, $%04x  ",
    "ret              ",
    "bvs $%04x        ",
    "tcall 7          ",
    "clr1 $%02x.3       ",
    "bbc $%02x.3, $%04x ",
    "cmp a, $%02x+x     ",
    "cmp a, $%04x+x   ",
    "cmp a, $%04x+y   ",
    "cmp a, [$%02x]+y   ",
    "cmp $%02x, #$%02x    ",
    "cmp [X], [Y]     ",
    "addw ya, $%02x     ",
    "ror $%02x+x        ",
    "ror a            ",
    "mov a, x         ",
    "cmp y, $%02x       ",
    "reti             ",
    "setc             ",
    "tcall 8          ",
    "set1 $%02x.4       ",
    "bbs $%02x.4, $%04x ",
    "adc a, $%02x       ",
    "adc a, $%04x     ",
    "adc a, [X]       ",
    "adc a, [$%02x+x]   ",
    "adc a, #$%02x      ",
    "adc $%02x, $%02x     ",
    "eor1 c, $%04x.%01x  ",
    "dec $%02x          ",
    "dec $%04x        ",
    "mov y, #$%02x      ",
    "pop p            ",
    "mov $%02x, #$%02x    ",
    "bcc $%04x        ",
    "tcall 9          ",
    "clr1 $%02x.4       ",
    "bbc $%02x.4, $%04x ",
    "adc a, $%02x+x     ",
    "adc a, $%04x+x   ",
    "adc a, $%04x+y   ",
    "adc a, [$%02x]+y   ",
    "adc $%02x, #$%02x    ",
    "adc [X], [Y]     ",
    "subw ya, $%02x     ",
    "dec $%02x+x        ",
    "dec a            ",
    "mov x, sp        ",
    "div ya, x        ",
    "xcn a            ",
    "ei               ",
    "tcall 10         ",
    "set1 $%02x.5       ",
    "bbs $%02x.5, $%04x ",
    "sbc a, $%02x       ",
    "sbc a, $%04x     ",
    "sbc a, [X]       ",
    "sbc a, [$%02x+x]   ",
    "sbc a, #$%02x      ",
    "sbc $%02x, $%02x     ",
    "mov1 c, $%04x.%01x  ",
    "inc $%02x          ",
    "inc $%04x        ",
    "cmp y, #$%02x      ",
    "pop a            ",
    "mov [x+], a      ",
    "bcs $%04x        ",
    "tcall 11         ",
    "clr1 $%02x.5       ",
    "bbc $%02x.5, $%04x ",
    "sbc a, $%02x+x     ",
    "sbc a, $%04x+x   ",
    "sbc a, $%04x+y   ",
    "sbc a, [$%02x]+y   ",
    "sbc $%02x, #$%02x    ",
    "sbc [X], [Y]     ",
    "movw ya, $%02x     ",
    "inc $%02x+x        ",
    "inc a            ",
    "mov sp, x        ",
    "das a            ",
    "mov a, [x+]      ",
    "di               ",
    "tcall 12         ",
    "set1 $%02x.6       ",
    "bbs $%02x.6, $%04x ",
    "mov $%02x, a       ",
    "mov $%04x, a     ",
    "mov [X], a       ",
    "mov [$%02x+x], a   ",
    "cmp x, #$%02x      ",
    "mov $%04x, x     ",
    "mov1 $%04x.%01x, c  ",
    "mov $%02x, y       ",
    "mov $%04x, y     ",
    "mov x, #$%02x      ",
    "pop x            ",
    "mul ya           ",
    "bne $%04x        ",
    "tcall 13         ",
    "clr1 $%02x.6       ",
    "bbc $%02x.6, $%04x ",
    "mov $%02x+x, a     ",
    "mov $%04x+x, a   ",
    "mov $%04x+y, a   ",
    "mov [$%02x]+y, a   ",
    "mov $%02x, x       ",
    "mov $%02x+y, x     ",
    "movw $%02x, ya     ",
    "mov $%02x+x, y     ",
    "dec y            ",
    "mov a, y         ",
    "cbne $%02x+x, $%04x",
    "daa a            ",
    "clrv             ",
    "tcall 14         ",
    "set1 $%02x.7       ",
    "bbs $%02x.7, $%04x ",
    "mov a, $%02x       ",
    "mov a, $%04x     ",
    "mov a, [X]       ",
    "mov a, [$%02x+x]   ",
    "mov a, #$%02x      ",
    "mov x, $%04x     ",
    "not1 $%04x.%01x     ",
    "mov y, $%02x       ",
    "mov y, $%04x     ",
    "notc             ",
    "pop y            ",
    "sleep            ",
    "beq $%04x        ",
    "tcall 15         ",
    "clr1 $%02x.7       ",
    "bbc $%02x.7, $%04x ",
    "mov a, $%02x+x     ",
    "mov a, $%04x+x   ",
    "mov a, $%04x+y   ",
    "mov a, [$%02x]+y   ",
    "mov x, $%02x       ",
    "mov x, $%02x+y     ",
    "mov $%02x, $%02x     ",
    "mov y, $%02x+x     ",
    "inc y            ",
    "mov y, a         ",
    "dbnz y, $%04x    ",
    "stop             ",
];

const SPC_OPCODE_TYPE: [u8; 256] = [
    0, 0, 1, 5, 1, 2, 0, 1, 1, 4, 6, 1, 2, 0, 2, 0, 3, 0, 1, 5, 1, 2, 2, 1, 4, 0, 1, 1, 0, 0, 2, 2,
    0, 0, 1, 5, 1, 2, 0, 1, 1, 4, 6, 1, 2, 0, 5, 3, 3, 0, 1, 5, 1, 2, 2, 1, 4, 0, 1, 1, 0, 0, 1, 2,
    0, 0, 1, 5, 1, 2, 0, 1, 1, 4, 6, 1, 2, 0, 2, 1, 3, 0, 1, 5, 1, 2, 2, 1, 4, 0, 1, 1, 0, 0, 2, 2,
    0, 0, 1, 5, 1, 2, 0, 1, 1, 4, 6, 1, 2, 0, 5, 0, 3, 0, 1, 5, 1, 2, 2, 1, 4, 0, 1, 1, 0, 0, 1, 0,
    0, 0, 1, 5, 1, 2, 0, 1, 1, 4, 6, 1, 2, 1, 0, 4, 3, 0, 1, 5, 1, 2, 2, 1, 4, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 1, 5, 1, 2, 0, 1, 1, 4, 6, 1, 2, 1, 0, 0, 3, 0, 1, 5, 1, 2, 2, 1, 4, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 1, 5, 1, 2, 0, 1, 1, 2, 6, 1, 2, 1, 0, 0, 3, 0, 1, 5, 1, 2, 2, 1, 1, 1, 1, 1, 0, 0, 5, 0,
    0, 0, 1, 5, 1, 2, 0, 1, 1, 2, 6, 1, 2, 0, 0, 0, 3, 0, 1, 5, 1, 2, 2, 1, 1, 1, 4, 1, 0, 0, 3, 0,
];

impl Snes {
    pub fn cpu_trace_line(&mut self) -> String {
        let dis_line = self.cpu_disassembly_line();
        format!(
            "CPU {:02x}:{:04x} {} A:{:04x} X:{:04x} Y:{:04x} SP:{:04x} DP:{:04x} DB:{:02x} {} {}{}{}{}{}{}{}{}",
            self.cpu.k,
            self.cpu.pc,
            dis_line,
            self.cpu.a,
            self.cpu.x,
            self.cpu.y,
            self.cpu.sp,
            self.cpu.dp,
            self.cpu.db,
            if self.cpu.e { 'E' } else { 'e' },
            if self.cpu.n { 'N' } else { 'n' },
            if self.cpu.v { 'V' } else { 'v' },
            if self.cpu.mf { 'M' } else { 'm' },
            if self.cpu.xf { 'X' } else { 'x' },
            if self.cpu.d { 'D' } else { 'd' },
            if self.cpu.i { 'I' } else { 'i' },
            if self.cpu.z { 'Z' } else { 'z' },
            if self.cpu.c { 'C' } else { 'c' },
        )
    }

    pub fn print_cpu_line(&mut self) {
        if self.debug_cycles {
            println!("{} 0x{:x}", self.cpu_trace_line(), self.ppu.vram[0]);
        }
    }

    fn cpu_disassembly_line(&mut self) -> String {
        let adr = self.cpu.pc as u32 | ((self.cpu.k as u32) << 16);
        let opcode = self.read(adr);
        let byte = self.read((adr + 1) & 0x00ff_ffff);
        let byte2 = self.read((adr + 2) & 0x00ff_ffff);
        let word = ((byte2 as u16) << 8) | byte as u16;
        let longv = ((self.read((adr + 3) & 0x00ff_ffff) as u32) << 16) | word as u32;
        let rel = self
            .cpu
            .pc
            .wrapping_add(2)
            .wrapping_add(byte as i8 as i16 as u16);
        let rell = self.cpu.pc.wrapping_add(3).wrapping_add(word as i16 as u16);

        match CPU_OPCODE_TYPE[opcode as usize] {
            0 => format_c_template(CPU_OPCODE_NAMES[opcode as usize], &[]),
            1 => format_c_template(CPU_OPCODE_NAMES[opcode as usize], &[byte as u32]),
            2 => format_c_template(CPU_OPCODE_NAMES[opcode as usize], &[word as u32]),
            3 => format_c_template(CPU_OPCODE_NAMES[opcode as usize], &[longv]),
            4 => {
                if self.cpu.mf {
                    format_c_template(
                        CPU_OPCODE_NAMES_SP[opcode as usize].unwrap(),
                        &[byte as u32],
                    )
                } else {
                    format_c_template(CPU_OPCODE_NAMES[opcode as usize], &[word as u32])
                }
            }
            5 => {
                if self.cpu.xf {
                    format_c_template(
                        CPU_OPCODE_NAMES_SP[opcode as usize].unwrap(),
                        &[byte as u32],
                    )
                } else {
                    format_c_template(CPU_OPCODE_NAMES[opcode as usize], &[word as u32])
                }
            }
            6 => format_c_template(CPU_OPCODE_NAMES[opcode as usize], &[rel as u32]),
            7 => format_c_template(CPU_OPCODE_NAMES[opcode as usize], &[rell as u32]),
            8 => format_c_template(
                CPU_OPCODE_NAMES[opcode as usize],
                &[byte2 as u32, byte as u32],
            ),
            _ => unreachable!(),
        }
    }
}

impl ApuState {
    pub fn spc_trace_line(&mut self) -> String {
        let dis_line = self.spc_disassembly_line();
        format!(
            "SPC {:04x} {} A:{:02x} X:{:02x} Y:{:02x} SP:{:02x} {}{}{}{}{}{}{}{}",
            self.spc.pc,
            dis_line,
            self.spc.a,
            self.spc.x,
            self.spc.y,
            self.spc.sp,
            if self.spc.n { 'N' } else { 'n' },
            if self.spc.v { 'V' } else { 'v' },
            if self.spc.p { 'P' } else { 'p' },
            if self.spc.b { 'B' } else { 'b' },
            if self.spc.h { 'H' } else { 'h' },
            if self.spc.i { 'I' } else { 'i' },
            if self.spc.z { 'Z' } else { 'z' },
            if self.spc.c { 'C' } else { 'c' },
        )
    }

    fn spc_disassembly_line(&mut self) -> String {
        let adr = self.spc.pc;
        let opcode = self.cpu_read(adr);
        let byte = self.cpu_read(adr.wrapping_add(1));
        let byte2 = self.cpu_read(adr.wrapping_add(2));
        let word = ((byte2 as u16) << 8) | byte as u16;
        let rel = self
            .spc
            .pc
            .wrapping_add(2)
            .wrapping_add(byte as i8 as i16 as u16);
        let rel2 = self
            .spc
            .pc
            .wrapping_add(2)
            .wrapping_add(byte2 as i8 as i16 as u16);
        let wordb = word & 0x1fff;
        let bit = word >> 13;

        match SPC_OPCODE_TYPE[opcode as usize] {
            0 => format_c_template(SPC_OPCODE_NAMES[opcode as usize], &[]),
            1 => format_c_template(SPC_OPCODE_NAMES[opcode as usize], &[byte as u32]),
            2 => format_c_template(SPC_OPCODE_NAMES[opcode as usize], &[word as u32]),
            3 => format_c_template(SPC_OPCODE_NAMES[opcode as usize], &[rel as u32]),
            4 => format_c_template(
                SPC_OPCODE_NAMES[opcode as usize],
                &[byte2 as u32, byte as u32],
            ),
            5 => format_c_template(
                SPC_OPCODE_NAMES[opcode as usize],
                &[byte as u32, rel2 as u32],
            ),
            6 => format_c_template(
                SPC_OPCODE_NAMES[opcode as usize],
                &[wordb as u32, bit as u32],
            ),
            _ => unreachable!(),
        }
    }
}

fn format_c_template(template: &str, args: &[u32]) -> String {
    let mut out = String::new();
    let mut arg_index = 0usize;
    let mut chars = template.chars().peekable();
    while let Some(ch) = chars.next() {
        if ch != '%' {
            out.push(ch);
            continue;
        }
        let mut zero_pad = false;
        if chars.peek() == Some(&'0') {
            zero_pad = true;
            chars.next();
        }
        let mut width = 0usize;
        while let Some(next) = chars.peek().copied() {
            if let Some(digit) = next.to_digit(10) {
                width = width * 10 + digit as usize;
                chars.next();
            } else {
                break;
            }
        }
        match chars.next() {
            Some('x') => {
                let value = args[arg_index];
                arg_index += 1;
                if zero_pad {
                    out.push_str(&format!("{value:0width$x}"));
                } else if width != 0 {
                    out.push_str(&format!("{value:width$x}"));
                } else {
                    out.push_str(&format!("{value:x}"));
                }
            }
            Some(other) => {
                out.push('%');
                out.push(other);
            }
            None => out.push('%'),
        }
    }
    out
}
