[package]
name = "zelda3"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autobins = false

[dependencies]
bincode = "1"
opus = "0.3.1"
serde = { version = "1", features = ["derive"] }
serde-big-array = "0.5"
snes = { path = "../snes" }
zelda3-compat = { path = "../zelda3-compat" }
zelda3-dialogue = { path = "../zelda3-dialogue" }
zelda3-palette = { path = "../zelda3-palette" }

[lints]
workspace = true
