//! CHR parity lock: sha1 of each sheet block's concatenated CHR index tiles.
//!
//! Mirrors the dialogue `messages.sha1` pattern: an unedited sheet compiles to a
//! byte-identical pack, so its per-block sha1 stays constant. Editing a tile
//! changes the block's sha1 and the build fails until the lock is re-blessed with
//! `zelda3 --bless-chr`.

use crate::sidecar::DecodedSheet;
use serde::{Deserialize, Serialize};
use sha1::{Digest, Sha1};
use std::collections::HashMap;

pub const FORMAT_CHR_SHA_LOCK: &str = "zelda3_chr_sha1_lock_v1";

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChrShaLock {
    pub format: String,
    #[serde(default, rename = "block")]
    pub blocks: Vec<ChrShaEntry>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChrShaEntry {
    pub sheet: String,
    pub block: String,
    pub source_kind: String,
    pub source_pack: u32,
    pub indices_sha1: String,
}

/// sha1 (lowercase hex) of a block's concatenated 64-byte index tile arrays.
fn block_indices_sha1(sheet: &DecodedSheet, block: &crate::sidecar::SidecarBlock) -> String {
    let mut hasher = Sha1::new();
    for tile in sheet.block_tiles(block) {
        hasher.update(tile);
    }
    let digest = hasher.finalize();
    let mut hex = String::with_capacity(40);
    for byte in digest {
        hex.push_str(&format!("{byte:02x}"));
    }
    hex
}

/// Build the parity lock structure from decoded sheets.
pub fn build_lock(sheets: &[DecodedSheet]) -> ChrShaLock {
    let mut blocks = Vec::new();
    for sheet in sheets {
        for block in &sheet.blocks {
            blocks.push(ChrShaEntry {
                sheet: sheet.name.clone(),
                block: block.block.clone(),
                source_kind: block.source_kind.clone(),
                source_pack: block.source_pack,
                indices_sha1: block_indices_sha1(sheet, block),
            });
        }
    }
    ChrShaLock {
        format: FORMAT_CHR_SHA_LOCK.to_string(),
        blocks,
    }
}

/// Serialize a lock as TOML with a machine-generated header comment.
pub fn serialize_lock(lock: &ChrShaLock) -> String {
    let mut out = String::new();
    out.push_str("# zelda3 CHR parity lock (machine-generated by `zelda3 --bless-chr`).\n");
    out.push_str("# One entry per editable sheet block; indices_sha1 pins the block's CHR\n");
    out.push_str("# tile indices so unedited sheets compile to byte-identical packs.\n");
    out.push_str(&format!("format = \"{}\"\n", lock.format));
    for entry in &lock.blocks {
        out.push_str("\n[[block]]\n");
        out.push_str(&format!("sheet = \"{}\"\n", entry.sheet));
        out.push_str(&format!("block = \"{}\"\n", entry.block));
        out.push_str(&format!("source_kind = \"{}\"\n", entry.source_kind));
        out.push_str(&format!("source_pack = {}\n", entry.source_pack));
        out.push_str(&format!("indices_sha1 = \"{}\"\n", entry.indices_sha1));
    }
    out
}

/// Regenerate the CHR parity lock TOML from decoded sheets (the `--bless-chr` step).
pub fn generate_sha_lock(sheets: &[DecodedSheet]) -> String {
    serialize_lock(&build_lock(sheets))
}

/// Parse a lock TOML document.
pub fn parse_lock(toml_str: &str) -> Result<ChrShaLock, String> {
    toml::from_str(toml_str).map_err(|err| format!("CHR parity lock parse failed: {err}"))
}

/// Verify decoded sheets against a lock document; on any drift or missing block,
/// return an error mirroring the dialogue lock's guidance.
pub fn verify_against_lock(sheets: &[DecodedSheet], lock_toml: &str) -> Result<(), String> {
    let lock = parse_lock(lock_toml)?;
    if lock.format != FORMAT_CHR_SHA_LOCK {
        return Err(format!(
            "CHR parity lock format is {}, expected {FORMAT_CHR_SHA_LOCK}",
            lock.format
        ));
    }
    let expected: HashMap<(&str, &str), &str> = lock
        .blocks
        .iter()
        .map(|entry| {
            (
                (entry.sheet.as_str(), entry.block.as_str()),
                entry.indices_sha1.as_str(),
            )
        })
        .collect();

    for sheet in sheets {
        for block in &sheet.blocks {
            let actual = block_indices_sha1(sheet, block);
            match expected.get(&(sheet.name.as_str(), block.block.as_str())) {
                Some(expected_sha1) => {
                    if !expected_sha1.eq_ignore_ascii_case(&actual) {
                        return Err(format!(
                            "block {} of sheet {} drifted from the parity lock: indices_sha1 is \
                             {expected_sha1} but the sheet compiles to {actual}; run \
                             `zelda3 --bless-chr` to accept the edit",
                            block.block, sheet.name
                        ));
                    }
                }
                None => {
                    return Err(format!(
                        "block {} of sheet {} is missing from the parity lock; run \
                         `zelda3 --bless-chr`",
                        block.block, sheet.name
                    ));
                }
            }
        }
    }
    Ok(())
}
