#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 6 ]]; then
  echo "usage: $0 CACHE_DIR ROM_PATH PAIRED_CHECKPOINT OUTPUT_DIR FRAMES_FROM_CHECKPOINT TRIAL_START_HOST" >&2
  exit 2
fi

cache_dir=$1
rom_path=$2
checkpoint=$3
output_dir=$4
frames=$5
trial_start=$6

exec env \
  ZELDA3_CACHED_AV_NATIVE_TIMING=1 \
  ZELDA3_NATIVE_EXACT_CPU_OWNER=1 \
  ZELDA3_NATIVE_EXACT_CPU_CONTIGUOUS_TRIAL_START="$trial_start" \
  ZELDA3_NATIVE_EXACT_CPU_REBASE_TRIAL_STACK=1 \
  ZELDA3_NATIVE_EXACT_CPU_REBASE_TRIAL_DP=1 \
  ZELDA3_NATIVE_EXACT_CPU_REBASE_TRIAL_DIALOGUE=1 \
  ZELDA3_NATIVE_EXACT_CPU_REBASE_TRIAL_OVERWORLD_SCRATCH=1 \
  ZELDA3_NATIVE_EXACT_CPU_REBASE_AFTER_CARRIED_NMI=1 \
  ZELDA3_NATIVE_EXACT_CPU_FLOOR_DRAW_LIVE_TRIAL=1 \
  ZELDA3_NATIVE_EXACT_CPU_OBJECT_DRAW_LIVE_TRIAL=1 \
  ZELDA3_NATIVE_EXACT_CPU_ROOM_HEADER_LIVE_TRIAL=1 \
  ZELDA3_NATIVE_EXACT_CPU_ROOM_UPLOAD_LIVE_TRIAL=1 \
  ZELDA3_NATIVE_EXACT_CPU_ITEM_RECEIPT_LIVE_TRIAL=1 \
  ZELDA3_NATIVE_EXACT_CPU_SPRITE_PREP_LIVE_TRIAL=1 \
  ZELDA3_NATIVE_EXACT_CPU_SCAN_LIVE_TRIAL=1 \
  ZELDA3_NATIVE_EXACT_CPU_SCAN_TRIAL=1 \
  ZELDA3_NATIVE_EXACT_CPU_SPOTLIGHT_LIVE_TRIAL=1 \
  ZELDA3_NATIVE_EXACT_CPU_BG_CHARS_GATE_LIVE_TRIAL=1 \
  ZELDA3_NATIVE_EXACT_CPU_DIAGNOSE_OWNERSHIP=1 \
  target/parity/zelda3 --replay-cached-snes9x-av \
  "$cache_dir" "$rom_path" "$output_dir" \
  --resume-paired "$checkpoint" --frames "$frames" --ignore-video
